<?php

namespace Acme\FriendshipBundle\Entity;

/**
 * RelationshipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelationshipRepository extends \Doctrine\ORM\EntityRepository
{
}
